### ISSUE TITLE
RestHub Modules Not available at https://oss.sonatype.org/content/repositories/snapshots

### ISSUE THREAD

**Issue by ffacon** [resthub/todo-backbone-example#12]
Hello,
As RestHub module 2.1.0 is released, perhaps it would be better for new commers (no snaspshot build locally) to add a ref to https://oss.sonatype.org/content/repositories/releases in a your pom.xml.
and resthub.version that could be different regarding the project.version
<properties>
        <resthub.version>2.1.0</resthub.version>

Regards
François

**Comment by bclozel** [comment]
Hello there!
All RESThub releases are synced to maven central. So there's no need to add oss/releases as a repository.

Regarding `project.version` vs `resthub.version`, I think my fellow contributors wanted to stress out the fact that this example project is in sync with RESThub development; and you should check out previous tags/versions if you want to test it with older RESThub versions.

Maybe I didn't get your PR?

**Comment by ffacon** [comment]
Hello,

My initial goal was to try your application out of the box

Currently, when I try to make a simple mvn jetty run on a clean maven repository, 
I get the following Error

Failed to execute goal on project todo-backbone: Could not resolve dependencies for project org.resthub.example:todo-backbone:war:2.1.0-SNAPSHOT: The following artifacts could not be resolved: org.resthub:resthub-mongodb:jar:2.1.0-SNAPSHOT, org.resthub:resthub-web-server:jar:2.1.0-SNAPSHOT, org.resthub:resthub-test:jar:2.1.0-SNAPSHOT: Could not find artifact org.resthub:resthub-mongodb:jar:2.1.0-SNAPSHOT in snapshot (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

There is only some tags for beta1 and for rc1 rc2
There is no previous tag for last release versions. 
This project seems to be out of sync with the current 2.1.1-SNAPSHOT.

My PR was a proposition to fix this problem as currently your demo is not working.
HTH
